import { useState, useEffect } from "react";
import AdminLayout from "./components/AdminLayout";
import {
  FaRobot,
  FaChartLine,
  FaPercentage,
  FaWallet,
  FaHistory,
  FaCogs,
  FaArrowUp,
  FaArrowDown
} from "react-icons/fa";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from "recharts";

const GTpayoutAnalytics = () => {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const fetchAnalytics = async () => {
    try {
      const res = await fetch("/api/admin-api.php", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ q: "admin_get_bot_analytics" }),
      });
      const json = await res.json();
      if (json.success) {
        setData(json);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div className="p-10 text-center animate-pulse">Loading Bot Analytics...</div>;

  const winRate = data?.stats?.total_trades > 0
    ? ((data.stats.won_trades / data.stats.total_trades) * 100).toFixed(1)
    : "0.0";

  return (
    <AdminLayout title="Bot Analytics">
    <div className="p-0 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">AI Bot Analytics</h1>
        <p className="text-sm text-slate-500">Global performance metrics for automated trading.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-blue-500/10 rounded-xl text-blue-500">
              <FaRobot size={20} />
            </div>
            <span className="text-[10px] font-bold text-slate-400 uppercase">Active Sessions</span>
          </div>
          <p className="text-2xl font-black text-slate-900 dark:text-white">{data?.stats?.active_sessions}</p>
          <p className="text-xs text-slate-500 mt-1">Users currently running bots</p>
        </div>

        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-emerald-500/10 rounded-xl text-emerald-500">
              <FaPercentage size={20} />
            </div>
            <span className="text-[10px] font-bold text-slate-400 uppercase">Win Rate</span>
          </div>
          <p className="text-2xl font-black text-emerald-500">{winRate}%</p>
          <p className="text-xs text-slate-500 mt-1">Based on {data?.stats?.total_trades} trades</p>
        </div>

        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-purple-500/10 rounded-xl text-purple-500">
              <FaArrowUp size={20} />
            </div>
            <span className="text-[10px] font-bold text-slate-400 uppercase">Total Bot PnL</span>
          </div>
          <p className={`text-2xl font-black ${data?.stats?.total_pnl >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
            {data?.stats?.total_pnl >= 0 ? '+' : ''}${parseFloat(data?.stats?.total_pnl || 0).toLocaleString()}
          </p>
          <p className="text-xs text-slate-500 mt-1">Net profit generated by AI</p>
        </div>

        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 bg-yellow-500/10 rounded-xl text-yellow-500">
              <FaHistory size={20} />
            </div>
            <span className="text-[10px] font-bold text-slate-400 uppercase">Total Bot Trades</span>
          </div>
          <p className="text-2xl font-black text-slate-900 dark:text-white">{data?.stats?.total_trades}</p>
          <p className="text-xs text-slate-500 mt-1">Lifetime bot executions</p>
        </div>
      </div>

      <div className="grid lg:grid-cols-1 gap-6">
        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
          <h3 className="text-lg font-bold mb-6">Bot Profit History (Last 7 Days)</h3>
          <div className="h-[350px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={data?.pnl_history?.reverse()}>
                <defs>
                  <linearGradient id="colorPnl" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                <XAxis
                  dataKey="date"
                  stroke="#94a3b8"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                />
                <YAxis
                  stroke="#94a3b8"
                  fontSize={12}
                  tickLine={false}
                  axisLine={false}
                  tickFormatter={(value) => `$${value}`}
                />
                <Tooltip
                  contentStyle={{ background: '#0f172a', border: 'none', borderRadius: '12px', color: '#fff' }}
                />
                <Area
                  type="monotone"
                  dataKey="pnl"
                  stroke="#10b981"
                  strokeWidth={3}
                  fillOpacity={1}
                  fill="url(#colorPnl)"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
    </AdminLayout>
  );
};

export default GTpayoutAnalytics;
